### ISSUE TITLE
Stack trace when project not under npm

### ISSUE THREAD

**Issue by jccollet** [SonarSource/SonarTS#170]
When running sonar-scanner on a standalone typescript project (not under nom) I get the stack trace below. Either it should work or it should clearly state this is not a supported case.

module.js:471
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jeanchristophecollet/tmp/TSTestProject/.sonar/sonarts-core/node_modules/tslint-sonarts/lib/runner/tsmetrics.js:23:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
...
ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.runMetrics(ExternalTypescriptSensor.java:114)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.execute(ExternalTypescriptSensor.java:91)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:87)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:81)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:67)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:75)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:178)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:259)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:254)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by tiramon** [comment]
i also get the
Error: Cannot find module 'typescript'
message

I try to run SonarScanner with the SonarTS Plugin installed
when i change into '.sonar\PROJECTNAME\soanrts-core' and execute a 'npm install typescript' there after it failed with sonarscanner and i rerun the node command given in the logoutput i get a valid json output

somehow the right typescript dep is not installed when started via sonarscanner

**Comment by inverno** [comment]
@tiramon you should not go into sonarts-core to run 'npm install typescript' you have to do it in your project's root folder, just like what you do for any other dependency of your project.
sonarscanner does not install any typescript dependency : the idea is that we use the same typescript compiler that is used by the project so that you don't get different results from the compiler and the analyzer.

Can you add typescript to your project and run sonarscanner again?

**Comment by scarrupt** [comment]
@inverno I have the same problem:

ERROR: External process failed with empty output: `node /PATHTOPROJECT/.scannerwork/sonarts-core/node_modules/tslint/bin/tslint --config /PATHTOPROJECT/.scannerwork/sonarts-core/tslint.json --format json --force --type-check --project /PATHTOPROJECT/tsconfig.json ...
12:11:10.722 DEBUG: module.js:491
    throw err;
    ^
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (PATHTOPROJECT/.scannerwork/sonarts-core/node_modules/tslint/lib/linter.js:20:10)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

My package.json file contains:

`
"devDependencies": {
...
"typescript": "^2.4.1",
...
}
`

I use sonar-scanner SonarQube Scanner 3.0.3.778 and SonarQube 6.5.0 (in docker)

**Comment by inverno** [comment]
@scarrupt did you run npm install?

**Comment by scarrupt** [comment]
@inverno I found the problem. I have a project with Typescript and Java source codes. I was running the sonar-scanner from the project root folder. If I run it inside the typescript source folder (where I did npm install), it works. Sorry about that.

**Comment by inverno** [comment]
@scarrupt you can also make your analysis multi-module, see the "Way #1" example in this page : https://docs.sonarqube.org/display/SCAN/Advanced+SonarQube+Scanner+Usages

This should allow you to run the scanner once and cover both java and typescript

**Comment by inverno** [comment]
@jtama thanks for the info. We will fix this one along with the rest.

**Comment by vilchik-elena** [comment]
Fixed by #195
