### ISSUE TITLE
ExternalTypescriptSensor: NullPointerException

### ISSUE THREAD

**Issue by tommueller** [SonarSource/SonarTS#188]
Running sonar-scanner on my angular-project ends with an error. My config looks like this:
```
sonar.projectKey=ng:core
sonar.projectName=ng-core
sonar.language=ts
sonar.sources=./src
```

it works if I omit the `sonar.language` setting, but then there is no relevant output (no code smells, etc. just 4 duplicates get detected).

This is the error:

```
ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.runMetrics(ExternalTypescriptSensor.java:160)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.execute(ExternalTypescriptSensor.java:105)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:184)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**Comment by inverno** [comment]
Hi @tommueller, thanks a lot for trying the analyzer during the feedback period!
I'm trying to reproduce the issue with a sample angular project, but no luck so far. Do you have a minimal reproducer to provide?

**Comment by tommueller** [comment]
Ok, I tracked this down, was an issue on my side. After figuring out that it only happend within our CI I eventually found out that I did not install tslint properly.
Maybe you could output an error "No external typescript sensor found" instead of the nullPointer ;)
Cheers!

**Comment by inverno** [comment]
@tommueller thanks for the update, but what you are saying does not really match up for me, let me explain :
1) tslint is embedded in the plugin, when you run the analysis, the plugin deploys tslint to a temporary folder and runs that. You should not have to install tslint at all and if you do the plugin will not point to it unless you also override the work directory property.
2) `runMetrics` which was the location of your error, is not part of tslint.

I would appreciate if you could tell me more about what you did exactly to fix your issue in CI

**Comment by tommueller** [comment]
@inverno Thanks for your feedback. I am running `sonar-scanner` within a docker-container: https://hub.docker.com/r/ciricihq/gitlab-sonar-scanner/
I added an extra stage for the scanner analysis, but forgot to install the npm dependencies in the stage. After installing the dependencies the error does not occur anymore. I assumed that it was missing the tslint-package, but then it might be any of those:

- codelyzer
- tslint
- tslint-loader
- tslint-sonarts
- typescript

Hope that helps!

**Comment by inverno** [comment]
Thanks @tommueller , for your information, the only project-dependency that is expected to be present before the analysis is typescript (because different projects will use different versions of the typescript compiler). I'll try see if I can reproduce your original problem by running the analysis without typescript present in the project.

**Comment by inverno** [comment]
@tommueller one final update : I reproduced your problem by removing typescript from my sample project. The changes that we had already made to logging make the issue a bit more obvious already (if you run the scanner with `-X`): accidentally it will read something very explicit, like `missing typescript`. I think we are fine.

**Comment by tommueller** [comment]
Perfect. Thanks a lot for looking into this.
