### ISSUE TITLE
Cannot find module 'typescript' with mixed Maven multi-module setup

### ISSUE THREAD

**Issue by muenchdo** [SonarSource/SonarTS#250]
Our project setup looks like this:
```
parent
  |_ module1/
    |_ module1-ui/src/app/... (TypeScript sources)
      |_ tsconfig.json
      |_ tslint.json
      |_ package.json
    |_ src/main/java/... (Java sources)
    |_ pom.xml
  |_ module2/...
  |_ pom.xml
```
I am running the analysis via `mvn sonar:sonar`. The configuration in the parent POM looks as follows:
```
<sonar.sources>.</sonar.sources>
<sonar.inclusions>src/main/java/**/*,*-ui/src/app/**/*</sonar.inclusions>
```
Despite having the TypeScript dependency in the package.json of the **-ui* frontend project, the rule analysis fails with this stacktrace:
```
module.js:529
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/j.doe/Dev/parent/module1/target/sonar/sonarts-core/node_modules/tslint/lib/linter.js:20:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by vilchik-elena** [comment]
@muenchdo try with [SonarTS 1.1.0-RC](https://github.com/SonarSource/SonarTS/releases/tag/1.1.0-RC1) 
Issue #195 is supposed to fix your problem

**Comment by musketyr** [comment]
@vilchik-elena I got the same problem and 1.0.0-RC fixed that. is the plugin going GA tomorrow?

**Comment by inverno** [comment]
@musketyr thanks for testing the RC! Indeed we should release tomorrow.

**Comment by muenchdo** [comment]
The latest release has resolved the issue for me, thank you!
