### ISSUE TITLE
SonarQube server + SonarTS with Jenkins Error when running tslint

### ISSUE THREAD

**Issue by Ugur22** [SonarSource/SonarTS#340]
**I want to report a bug.**
Im running a Sonarqube server on a docker that is connected to Jenkins with sonar-scanner. The sonarQube server seems to work fine but everytime I execute a build I get the following error:

`ERROR: Failed to run external process node /var/jenkins_home/workspace/sonarQube/.scannerwork/sonarts-core/node_modules/tslint-sonarts/bin/tsmetrics. As a result, NO METRICS WERE GENERATED` 

**SonarTS version:** 1.2.0<br>
**TypeScript version:**  2.0.3 <br>

**SonarQube version:** 6.5<br>
**TSLint version:** 4.3.0<br>

so I installed the Sonarqube server(2.5) plugin on Jenkins and connect that with the sonar-scanner(3.0.3.778). The Sonarqube server is installed on a docker image that includes SonarTS.

this is how my sonar-project.properties looks like:

```
sonar.projectKey=my:tslint-example
sonar.projectName=tslint-example
sonar.projectVersion=1.0
sonar.projectDescription= Project test results.

sonar.java.version=1.8

sonar.language=ts
sonar.sources=src/app


sonar.exclusions=node_modules/**`
```

When I create a build and run it I get the following log:

```
Dsonar.projectBaseDir=/var/jenkins_home/workspace/sonarQube
INFO: Option -e/--errors is no longer supported and will be ignored
INFO: Scanner configuration file: /var/jenkins_home/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonar_Scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /var/jenkins_home/workspace/sonarQube/sonar-project.properties
INFO: SonarQube Scanner 3.0.3.778
INFO: Java 1.8.0 Oracle Corporation (64-bit)
INFO: Linux 3.16.0-4-amd64 amd64
INFO: User cache: /var/jenkins_home/.sonar/cache
INFO: Load global settings
INFO: Load global settings (done) | time=263ms
INFO: User cache: /var/jenkins_home/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=22ms
INFO: SonarQube server 6.5.0
INFO: Default locale: "en", source code encoding: "UTF-8" (analysis is platform dependent)
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=146ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=34ms
INFO: Load active rules
INFO: Load active rules (done) | time=1761ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=197ms
INFO: Publish mode
INFO: Project key: my:tslint-example
INFO: -------------  Scan tslint-example
INFO: Load server rules
INFO: Load server rules (done) | time=675ms
INFO: Language is forced to ts
INFO: Base dir: /var/jenkins_home/workspace/sonarQube
INFO: Working dir: /var/jenkins_home/workspace/sonarQube/.scannerwork
INFO: Source paths: src/app
INFO: Source encoding: UTF-8, default locale: en
INFO: Index files
INFO: Excluded sources: 
INFO:   node_modules/**
WARN: File '/var/jenkins_home/workspace/sonarQube/src/app/home/home.component.css' is ignored because it doesn't belong to the forced language 'ts'
WARN: File '/var/jenkins_home/workspace/sonarQube/src/app/home/home.component.html' is ignored because it doesn't belong to the forced language 'ts'
WARN: File '/var/jenkins_home/workspace/sonarQube/src/app/app.component.css' is ignored because it doesn't belong to the forced language 'ts'
WARN: File '/var/jenkins_home/workspace/sonarQube/src/app/app.component.html' is ignored because it doesn't belong to the forced language 'ts'
INFO: 5 files indexed
INFO: 0 files ignored because of inclusion/exclusion patterns
INFO: Quality profile for ts: Sonar way
INFO: Sensor SonarJavaXmlFileSensor [java]
INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=0ms
INFO: Sensor Analyzer for "php.ini" files [php]
INFO: Sensor Analyzer for "php.ini" files [php] (done) | time=5ms
INFO: Sensor TypeScript Sensor [typescript]
INFO: Metrics calculation
ERROR: Failed to run external process `node /var/jenkins_home/workspace/sonarQube/.scannerwork/sonarts-core/node_modules/tslint-sonarts/bin/tsmetrics`. As a result, NO METRICS WERE GENERATED, run with -X for more information
java.io.IOException: Cannot run program "node": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.runMetricsProcess(ExternalTypescriptSensor.java:185)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.runMetrics(ExternalTypescriptSensor.java:160)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.execute(ExternalTypescriptSensor.java:107)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:179)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:261)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:256)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:245)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:119)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1023)
	... 34 common frames omitted

INFO: Rules execution
INFO: Running rule analysis for `/var/jenkins_home/workspace/sonarQube/src/tsconfig.json` with 5 files
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 36.990s
INFO: Final Memory: 43M/90M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Failed to run external process `node /var/jenkins_home/workspace/sonarQube/.scannerwork/sonarts-core/node_modules/tslint/bin/tslint --config /var/jenkins_home/workspace/sonarQube/.scannerwork/sonarts-core/tslint.json --format json --force --type-check --project /var/jenkins_home/workspace/sonarQube/src/tsconfig.json /var/jenkins_home/workspace/sonarQube/src/app/app.component.spec.ts /var/jenkins_home/workspace/sonarQube/src/app/app.component.ts /var/jenkins_home/workspace/sonarQube/src/app/app.module.ts /var/jenkins_home/workspace/sonarQube/src/app/home/home.component.spec.ts /var/jenkins_home/workspace/sonarQube/src/app/home/home.component.ts`
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.runRulesProcess(ExternalTypescriptSensor.java:243)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.runRules(ExternalTypescriptSensor.java:126)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.execute(ExternalTypescriptSensor.java:113)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:179)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:261)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:256)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:245)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:119)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.io.IOException: Cannot run program "node": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.runRulesProcess(ExternalTypescriptSensor.java:218)
	... 33 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1023)
	... 34 more
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
ERROR: SonarQube scanner exited with non-zero code: 1
Finished: FAILURE
```
If I run this build with `sonar.language=js` included in my sonar config the build works fine.

The thing is if I run the exact same setup on my local machine without Jenkins it works fine. anybody know if this is a bug?

**Comment by vilchik-elena** [comment]
Hi @Ugur22 
First, I think you don't use SonarTS 1.2, but SonarTS 1.0
Second, looks like you don't have nodejs installed in your environment -> `Cannot run program "node": error=2, No such file or directory`

**Comment by Ugur22** [comment]
oke I will try to install it on my jenkins server. Another thing when I run it on my local machine I don't get the same error but SonarQube server does not show any code smells even though when I run tslint in the command line I do see a bunch of warnings.

**Comment by vilchik-elena** [comment]
@Ugur22 SonarTS is not tslint integration in SonarQube, while it embeds some of tslint rules.
First check that metrics appeared on ts files (lines of code or syntax highlighting for example).
Then try to activate more rules or just set `Sonar Way Recommended` profile instead of `Sonar Way`.

**Comment by Ugur22** [comment]
I got it working now with Node.js this issue can be closed
