### ISSUE TITLE
TypeScript analyse failed

### ISSUE THREAD

**Issue by burtsevyg** [SonarSource/SonarTS#433]
**I want to report a bug.**

**SonarTS version:1.4 (build 1932)** <br>
**Node.js version:v6.11.2** <br>
**TypeScript version:2.6.2** <br>

**SonarQube version:6.7.1** <br>
**SonarLint version and used IDE:** <br>
**TSLint version:4.5.1** <br>

**Rule key:** 

**Reproducer**
I tried analyse my project with frontend-maven-plugin and angular.

In my pom.xml I have

```
  <properties>
    <sonar.exclusions>dist/**/*,node_modules/**/*,dll/**/*,target/**/*</sonar.exclusions>
    <sonar.sources>.</sonar.sources>
  </properties>
```
In Jenkinsfile:

```
            stage('SonarQube analysis') {
              withSonarQubeEnv('SonarQube') {
                sh "mvn -e -X org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar -Dsonar.branch=${env.BRANCH_NAME}"
              }
            }
```

**Logs**
```

> [ERROR] 20:05:46.172         Object.entries(element).forEach(([key, value]) => {
> [ERROR] 20:05:46.172                ^
> [ERROR] 20:05:46.172 
> [ERROR] 20:05:46.172 TypeError: Object.entries is not a function
> [ERROR] 20:05:46.172     at data.forEach (/home/jenkins/data/workspace/test_master-KH6NFHZTKMFYQV4MLW65EVA2UT76KHSMVHSWZU5BOTX2UEGCFAVQ/target/sonar/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/sonarUtils.js:17:16)
> [ERROR] 20:05:46.172     at Array.forEach (native)
> [ERROR] 20:05:46.172     at Object.stringifyToStream (/home/jenkins/data/workspace/test_master-KH6NFHZTKMFYQV4MLW65EVA2UT76KHSMVHSWZU5BOTX2UEGCFAVQ/target/sonar/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/sonarUtils.js:14:10)
> [ERROR] 20:05:46.172     at Socket.process.stdin.on (/home/jenkins/data/workspace/test_master-KH6NFHZTKMFYQV4MLW65EVA2UT76KHSMVHSWZU5BOTX2UEGCFAVQ/target/sonar/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/tsrunner.js:33:18)
> [ERROR] 20:05:46.172     at emitNone (events.js:91:20)
> [ERROR] 20:05:46.172     at Socket.emit (events.js:185:7)
> [ERROR] 20:05:46.172     at endReadableNT (_stream_readable.js:974:12)
> [ERROR] 20:05:46.172     at _combinedTickCallback (internal/process/next_tick.js:80:11)
> [ERROR] 20:05:46.172     at process._tickCallback (internal/process/next_tick.js:104:9)

```

Full log:
https://gist.github.com/burtsevyg/b1d7b998e16a1e98ac844d49f819ded0

**Comment by burtsevyg** [comment]
dublicate https://github.com/SonarSource/SonarTS/issues/432
