### ISSUE TITLE
SonarLint in Eclipse is slow due to failure in SonarTS

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarTS#547]
SonarTS will slowdown SonarLint analysis in Eclipse, because there is no typescript available.

```
No value provided by SonarLint for TypeScript location; property sonar.typescript.internal.typescriptLocation is missing
module.js:557
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/julien/Prog/workspace/.metadata/.plugins/org.eclipse.core.resources/.projects/sonar-branch-plugin/org.sonarlint.eclipse.core/.sonartmp/530654892781510723/sonarts-bundle/node_modules/tslint/lib/linter.js:20:10)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
Failed to start SonarTS Server
java.net.SocketTimeoutException: Accept timed out
        at java.net.PlainSocketImpl.socketAccept(Native Method) ~[na:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409) ~[na:1.8.0_144]
        at java.net.ServerSocket.implAccept(ServerSocket.java:545) ~[na:1.8.0_144]
        at java.net.ServerSocket.accept(ServerSocket.java:513) ~[na:1.8.0_144]
        at org.sonar.plugin.typescript.ContextualServer.startSonarTSServer(ContextualServer.java:109) [sonar-typescript-plugin-1.5.0.2122.jar:na]
        at org.sonar.plugin.typescript.ContextualServer.start(ContextualServer.java:82) [sonar-typescript-plugin-1.5.0.2122.jar:na]
```

**Comment by BayrekMokni** [comment]
Hello,
The same problem in Intellij.

**Comment by vilchik-elena** [comment]
@BayrekMokni please create a new issue with details (versions, connected/not connected mode etc)
