### ISSUE TITLE
no-identical-functions rule: Error: Not found child with kind Identifier

### ISSUE THREAD

**Issue by aaleksandrov** [SonarSource/SonarTS#671]
**I want to report a bug.**

**SonarTS version:** 1.7.0<br>
**Node.js version:** v8.11.3<br>
**TypeScript version:** 2.9.2<br>

**TSLint version:** 5.10.0<br>

**Rule key:** no-identical-functions

**Reproducer** 
All irrelevant code is removed from this class.
```
import 'mocha';
import { suite, test } from 'mocha-typescript';
import axios, {AxiosInstance} from 'axios';

@suite
export class MenusControllerTest {
  private readonly platformKey = 'some-plaftorm;
  private readonly restaurantId = '123456';
  private axios: AxiosInstance;

  before() {
    this.axios = axios.create({
      baseURL: 'http://localhost:4000',
      headers: {
        'content-type': 'application/json',
      },
    });
  }

  @test async 'Respond with menus'() {
    await this.axios.get(`/v1/platforms/${this.platformKey}/restaurants/${this.restaurantId}/menus`, {
      headers: {
        authorization: 'some-auth-header2',
      },
    });
  }

  @test async 'Respond not found for uapi empty response'() {
    await this.axios.get(`/v1/platforms/${this.platformKey}/restaurants/${this.restaurantId}/menus`, {
      headers: {
        authorization: 'some-auth-header3',
      },
    });
  }
}
```

**Logs**
```
$ tslint --project tsconfig.json "./**/*.ts" -e "./node_modules/**/*"   
The 'no-identical-functions' rule threw an error in '/home/alex/work/portal-menu-service/test/system/MenusControllerList.spec.ts':
Error: Not found child with kind Identifier
    at Object.findChild (/home/alex/work/portal-menu-service/node_modules/tslint-sonarts/lib/utils/navigation.js:166:15)
    at Function.issueNode (/home/alex/work/portal-menu-service/node_modules/tslint-sonarts/lib/rules/noIdenticalFunctionsRule.js:59:33)
    at Rule.apply (/home/alex/work/portal-menu-service/node_modules/tslint-sonarts/lib/rules/noIdenticalFunctionsRule.js:42:40)
    at Linter.applyRule (/home/alex/work/portal-menu-service/node_modules/tslint/lib/linter.js:197:29)
    at /home/alex/work/portal-menu-service/node_modules/tslint/lib/linter.js:139:85
    at Object.flatMap (/home/alex/work/portal-menu-service/node_modules/tslint/lib/utils.js:151:29)
    at Linter.getAllFailures (/home/alex/work/portal-menu-service/node_modules/tslint/lib/linter.js:139:32)
    at Linter.lint (/home/alex/work/portal-menu-service/node_modules/tslint/lib/linter.js:99:33)
    at /home/alex/work/portal-menu-service/node_modules/tslint/lib/runner.js:209:32
    at step (/home/alex/work/portal-menu-service/node_modules/tslib/tslib.js:133:27)
```

**Expected behavior**
Error shouldn't be thrown

**Comment by saberduck** [comment]
Hello @aaleksandrov ,

I confirm this issue, we will fix it in the next release. Thanks for reporting it.
