### ISSUE TITLE
sonarTS crashes

### ISSUE THREAD

**Issue by geetee24** [SonarSource/SonarTS#678]
**I want to report a bug.**

can you tell me what is causing this error?  FILE not found. What file?

bash-4.2# sonar-scanner
INFO: Scanner configuration file: /sonar-scanner-3.2.0.1227-linux/conf/sonar-scanner.properties
INFO: Project root configuration file: /gapy/sonar-project.properties
INFO: SonarQube Scanner 3.2.0.1227
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Linux 4.9.87-linuxkit-aufs amd64
INFO: User cache: /root/.sonar/cache
INFO: SonarQube server 7.1.0
INFO: Default locale: "en_US", source code encoding: "US-ASCII" (analysis is platform dependent)
INFO: Publish mode
INFO: Load global settings
INFO: Load global settings (done) | time=528ms
INFO: Server id: AWMnDe0-UFkcr8yjabhy
INFO: User cache: /root/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=297ms
INFO: Load/download plugins
INFO: Load/download plugins (done) | time=277ms
INFO: Process project properties
INFO: Execute project builders
INFO: Execute project builders (done) | time=5ms
INFO: Load project branches
INFO: Load project branches (done) | time=243ms
INFO: Load project pull requests
INFO: Load project pull requests (done) | time=226ms
INFO: Load branch configuration
INFO: Load branch configuration (done) | time=3ms
INFO: Load project repositories
INFO: Load project repositories (done) | time=360ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=386ms
INFO: Load active rules
INFO: Load active rules (done) | time=11633ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=404ms
WARN: SCM provider autodetection failed. No SCM provider claims to support this project. Please use sonar.scm.provider t
o define SCM of your project.
INFO: Project key: gst:SonarTest
INFO: Project base dir: /gapy
INFO: -------------  Scan GST Sonar Test
INFO: Base dir: /gapy
INFO: Working dir: /gapy/.scannerwork
INFO: Source paths: src/app
INFO: Source encoding: US-ASCII, default locale: en_US
INFO: Load server rules
INFO: Load server rules (done) | time=8290ms
INFO: Index files
INFO: Excluded sources:
INFO:   **/*.module.ts
INFO:   **/*.spec.ts
INFO: Included tests:
INFO:   **/*.spec.ts
INFO: 6 files indexed
INFO: 2 files ignored because of inclusion/exclusion patterns
INFO: Quality profile for ts: Sonar way
INFO: Sensor SonarJavaXmlFileSensor [java]
INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=2ms
INFO: Sensor SonarTS [typescript]
ERROR: Fat java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
java.io.at java.lang.Runtime.exec(Runtime.java:620)or=2, No such file or directory
        at java.lang.Runtime.exec(Runtime.java:347)
        at org.sonar.plugin.typescript.ExternalTypescriptSensor.analyze(ExternalTypescriptSensor.java:115)Sensor.java:15
5)      at org.sonar.plugin.typescript.ExternalTypescriptSensor.execute(ExternalTypescriptSensor.java:109)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)ava:135)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:297)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)entContainer.java:121)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)va:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)ncher.execute(BatchIsolatedLauncher.java:46)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)eddedScanner.java:128)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)75)
Caused bat java.lang.UNIXProcess.forkAndExec(Native Method)rectory
        at java.lang.ProcessImpl.start(ProcessImpl.java:134))
        ... 38 common frames omittedstart(ProcessBuilder.java:1029)

ERROR: No TypeScript files will be analyzed
INFO: Sensor SonarTS [typescript] (done) | time=277ms
INFO: Sensor SonarTS Coverage [typescript]
INFO: Sensor SonarTS Coverage [typescript] (done) | time=1ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=19ms
INFO: Sensor CPD Block Indexer
INFO: Sensor CPD Block Indexer (done) | time=0ms
INFO: No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
INFO: Calculating CPD for 0 files
INFO: CPD calculation finished
INFO: Analysis report generated in 183ms, dir size=57 KB
INFO: Analysis reports compressed in 19ms, zip size=15 KB
INFO: Analysis report uploaded in 230ms
INFO: ANALYSIS SUCCESSFUL, you can browse http://172.31.18.10:9000/dashboard/index/gst:SonarTest
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis re
port
INFO: More about the report processing at http://172.31.18.10:9000/api/ce/task?id=AWTJIjyAfOCBg81CTqjv
INFO: Task total time: 27.243 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 31.594s
INFO: Final Memory: 27M/174M
INFO: ------------------------------------------------------------------------
bash-4.2#

**SonarTS version:** <br>
**Node.js version:** <br>
**TypeScript version:** <br>

**SonarQube version:** <br>
**SonarLint version and used IDE:** <br>
**TSLint version:** <br>

**Rule key:** 

**Reproducer** 
```
// minimal reproducer if relevant
console.log("Hello, world"); // False-positive here
```

**Logs**
```
// logs of analysis if relevant
```

**Expected behavior**

**I want to provide the following feedback.**

**Rule key:** 

**Example**

**Comment by saberduck** [comment]
Do you have nodejs available on the machine where you run analysis? Please provide version of SonarTS and run in debug mode (add `-X` to `sonar-scanner` )

**Comment by geetee24** [comment]
did not have nodejs,  Did the docs request that? Now that I installed nodejs, the eror goes away.    new problem.  SonarTS will NOT detect intentional smells in my code. Any ideas?
