### ISSUE TITLE
No TypeScript compiler found in your project, analysis of typescript files is aborted

### ISSUE THREAD

**Issue by ZedProg** [SonarSource/SonarTS#689]
I have configured sonarqube in a VM(Windows Server 2012 R2) which is the build agent for VSTS. Then tried to run code quality check during the build process but is getting the below warning: 

`No Typescript compiler found in your project, analysis of typescript files is aborted.
`
Although the build is continuing, the sonarqube doesn't analyse any TS files.

SonarQube version: 6.7.4
 SonarTS version: 1.1.0.1079
Node.js 0.12.2.0 (I tried installing  Node.js 8 and 8+ version. but i was getting error that 0.12.2.0 is not supported and would require 8 or 8+ even after installing them. So rolled back to the previous form,)
TS in the VM: Typescript 1.7.6.0

I referred the thread https://github.com/SonarSource/SonarTS/releases/tag/1.2.0-RC1 and tried to install the `sonar-typescript-plugin-1.2.0.1467.jar` , but i am getting the below error: 
`No main manifest Attritbue in D:\sonar-typescript-plugin-1.2.0.1467.jar`

Any help of the same please?

**Comment by stas-vilchik** [comment]
Hi @ZedProg,

First, you absolutely need node 8 or later. Second, you need to install TypeScript locally into your project using `npm` or `yarn` (see [TypeScript in 5 minutes](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html) tutorial).

After that please read the [Installing a Plugin](https://docs.sonarqube.org/display/SONARQUBE67/Installing+a+Plugin) documentation to correctly install the SonarTS analyzer.

**Comment by ZedProg** [comment]
Thanks for the reply. The last part of the web.log file is as below, i believe it contains the error details:

```
2018.08.15 12:51:34 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarTS / 1.7.0.2893 / 0d296cae94240b183a0b3ae6e1a409a60fe9f865
2018.08.15 12:51:34 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarXML / 1.4.3.1027 / 39588245cecf538bb27be4e496ff303b0143d20b
2018.08.15 12:51:35 INFO  web[][o.s.s.p.d.m.c.MssqlCharsetHandler] Verify that database collation is case-sensitive and accent-sensitive
2018.08.15 12:51:36 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.ws.WebServiceFilter@6f930b0f [pattern=UrlPattern{inclusions=[/api/system/migrate_db/*, ...], exclusions=[/api/properties*, ...]}]
2018.08.15 12:51:36 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2018.08.15 12:51:39 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin Governance [governance]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:88)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:582)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Unable to register extension com.sonar.governance.H.D from plugin 'governance'
	at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:241)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtension(ServerExtensionInstaller.java:125)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:80)
	... 9 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Lorg/sonar/server/permission/PermissionService;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at org.picocontainer.injectors.AdaptingInjection$2.run(AdaptingInjection.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.picocontainer.injectors.AdaptingInjection.injectionFieldAnnotated(AdaptingInjection.java:209)
	at org.picocontainer.injectors.AdaptingInjection.fieldAnnotatedInjectionAdapter(AdaptingInjection.java:188)
	at org.picocontainer.injectors.AdaptingInjection.createComponentAdapter(AdaptingInjection.java:57)
	at org.picocontainer.behaviors.AbstractBehaviorFactory.createComponentAdapter(AbstractBehaviorFactory.java:44)
	at org.picocontainer.behaviors.OptInCaching.createComponentAdapter(OptInCaching.java:45)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:536)
	at org.picocontainer.DefaultPicoContainer.access$300(DefaultPicoContainer.java:84)
	at org.picocontainer.DefaultPicoContainer$AsPropertiesPicoContainer.addComponent(DefaultPicoContainer.java:1149)
	at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:239)
	... 11 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.server.permission.PermissionService
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 25 common frames omitted
2018.08.15 12:51:39 INFO  web[][o.s.p.StopWatcher] Stopping process
2018.08.15 12:51:40 INFO  web[][o.a.c.c.StandardWrapper] Waiting for [1] instance(s) to be deallocated for Servlet [default]
```

and no ce.log file is generated for the error occurred date,

**Comment by stas-vilchik** [comment]
Well, for the record, this is not a SonarTS error 😉 

Something is messed up with your plugins. Try to unpack SonarQube again and start a fresh instance.

**Comment by vilchik-elena** [comment]
If problem continues you can get help on https://community.sonarsource.org/
