### ISSUE TITLE
Type error when running sonarts as tslint extension

### ISSUE THREAD

**Issue by alban-auzeill** [SonarSource/SonarTS#735]
tslint 5.11.0
tsc 2.2.2
```
The 'no-return-type-any' rule threw an error in '/tmp/ag-grid/src/ts/widgets/componentAnnotations.ts':
TypeError: node.forEachChild is not a function
    at visitNode (/tmp/ag-grid/node_modules/tslint-sonarts/lib/rules/noReturnTypeAnyRule.js:64:22)
    at Visitor.getAllReturns (/tmp/ag-grid/node_modules/tslint-sonarts/lib/rules/noReturnTypeAnyRule.js:67:9)
    at Visitor.visitFunctionDeclaration (/tmp/ag-grid/node_modules/tslint-sonarts/lib/rules/noReturnTypeAnyRule.js:50:34)
    at Visitor.visitFunctionLikeDeclaration (/tmp/ag-grid/node_modules/tslint-sonarts/lib/utils/visitor.js:301:22)
    at Visitor.visitNode (/tmp/ag-grid/node_modules/tslint-sonarts/lib/utils/visitor.js:572:22)
    at ts.forEachChild.child (/tmp/ag-grid/node_modules/tslint-sonarts/lib/utils/visitor.js:579:45)
    at visitEachNode (/tmp/ag-grid/node_modules/typescript/lib/typescript.js:14209:30)
    at Object.forEachChild (/tmp/ag-grid/node_modules/typescript/lib/typescript.js:14382:24)
    at Visitor.visitChildren (/tmp/ag-grid/node_modules/tslint-sonarts/lib/utils/visitor.js:579:12)
    at Visitor.visitSourceFile (/tmp/ag-grid/node_modules/tslint-sonarts/lib/utils/visitor.js:242:14)
```

**Comment by vilchik-elena** [comment]
`Node. forEachChild` is available since TS 2.3
