### ISSUE TITLE
Error: Cannot find module 'typescript' on multi-modules project

### ISSUE THREAD

**Issue by sichida** [SonarSource/SonarTS#761]
**I want to report a bug.**

I get the error **Cannot find module 'typescript'** when running sonar on multi-modules project including java, javascript and typescript source files.

**SonarTS version:** 1.8<br>
**Node.js version:** v8.9.0<br>
**TypeScript version:** 2.9.2<br>

**SonarQube version:** 6.7.5<br>
**TSLint version:** 5.11.0<br>

**Reproducer** 
Please find below my project structure
```
my-project/
	|- pom.xml				/* Parent */
	|- my-project-sub-module-java/
		|- pom.xml
		|- src/				/* Backend source files */
	|- my-project-sub-module-ui/
		|- pom.xml
		|- package.json
		|- src/				/* UI source files using Typescript */

```

**Logs**
```
[ERROR] module.js:538
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module 'typescript'
[ERROR]     at Function.Module._resolveFilename (module.js:536:15)
[ERROR]     at Function.Module._load (module.js:466:25)
[ERROR]     at Module.require (module.js:579:17)
[ERROR]     at require (internal/module.js:11:18)
[ERROR]     at Object.<anonymous> (my-project\my-project-sub-module-ui\target\sonar\sonarts-bundle\node_modules\tslint\lib\language\walker\blockScopeAwareRuleWalker.js:20:10)
[ERROR]     at Module._compile (module.js:635:30)
[ERROR]     at Object.Module._extensions..js (module.js:646:10)
[ERROR]     at Module.load (module.js:554:32)
[ERROR]     at tryModuleLoad (module.js:497:12)
[ERROR]     at Function.Module._load (module.js:489:3)
[ERROR] Failed to find 'typescript' module. Please check, NODE_PATH contains location of global 'typescript' or install locally in your project
```

**I want to provide the following feedback.**
Dependency _typescript_ is defined in **devDependencies** section of my package.json

I am using **jacoco** code coverage plugin.

Thanks for your help

**Comment by sichida** [comment]
Forget my request, my CI job wasn't running `npm install` so there wasn't any typescript module within my project path.
