### ISSUE TITLE
Analysis shouldn't fail when node is missing

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarTS#830]
Currently when node is missing we will fail the whole analysis. We should just use feature of SQ 7.4 to log the warning, but we shouldn't fail the analysis.

Note that we had this behavior before (see #339 ,  #408 ) , but it was changed in some refactoring later on.

Stacktrace when node is not available
```
16:10:40.035 ERROR: Error during SonarQube Scanner execution                                                                                                                              
java.lang.IllegalStateException: Failed to get Node.js version.No TypeScript files will be analyzed. You can exclude TypeScript files from analysis with 'sonar.exclusions' property.     
        at org.sonar.plugin.typescript.ExternalTypescriptSensor.checkCompatibleNodeVersion(ExternalTypescriptSensor.java:163)                                                             
        at org.sonar.plugin.typescript.ExternalTypescriptSensor.analyze(ExternalTypescriptSensor.java:117)                                                                                
        at org.sonar.plugin.typescript.ExternalTypescriptSensor.execute(ExternalTypescriptSensor.java:111)                                                                                
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)                                                                                          
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)                                                                                          
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)                                                                                 
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)                                                                               
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)                                                                                          
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)                                                                                           
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)                                                                                        
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)                                                                                                
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:408)                                                                                                
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:403)                                                                                     
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:360)                                                                                        
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)                                                                                        
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)                                                                                                
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:126)                                                                                             
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)                                                                                        
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)                                                                                                
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)                                                                                                                    
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)                                                                                                                      
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)                                                                        
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                    
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                  
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                          
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                               
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)                                                                               
        at com.sun.proxy.$Proxy0.execute(Unknown Source)                                                                                                                                  
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)                                                                                                
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)                                                                                                  
        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)                                                                                                                        
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)                                                                                                                         
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)                                                                                                                            
Caused by: java.io.IOException: Cannot run program "node": CreateProcess error=2, The system cannot find the file specified                                                               
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)                                                                                                                       
        at java.lang.Runtime.exec(Runtime.java:620)                                                                                                                                       
        at java.lang.Runtime.exec(Runtime.java:450)                                                                                                                                       
        at java.lang.Runtime.exec(Runtime.java:347)                                                                                                                                       
        at org.sonar.plugin.typescript.ExternalTypescriptSensor.checkCompatibleNodeVersion(ExternalTypescriptSensor.java:158)                                                             
        ... 32 more                                                                                                                                                                       
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified                                                                                          
        at java.lang.ProcessImpl.create(Native Method)                                                                                                                                    
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)                                                                                                                             
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)                                                                                                                              
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)                                                                                                                       
        ... 36 more                                                                                                                                                                       
```

**Comment by saberduck** [comment]
obsolete
