### ISSUE TITLE
arguments-order rule threw an error

### ISSUE THREAD

**Issue by ariel7342** [SonarSource/SonarTS#836]
**I want to report a bug.**
I want to report a bug where 'arguments-order' rule threw an error for a specific code. 

**SonarTS version:** 1.9.0<br>
**Node.js version:** 10.14.2<br>
**TypeScript version:** 3.3.3333<br>

**TSLint version:** 5.13.1<br>

**Rule key:** 'arguments-order' 

**Reproducer** 
```
const params = {
  name: 'name',
};
expect('string').toHaveBeenCalledWith('something to test', params);

```

**Logs**
```
The 'arguments-order' rule threw an error in '/Users/ariell/Projects/client/page/src/components/Options/Options.spec.ts':
TypeError: Cannot read property 'name' of undefined
    at Visitor.getSwappedPairArgument (node_modules/tslint-sonarts/lib/rules/argumentsOrderRule.js:68:47)
    at Visitor.visitCallExpression (node_modules/tslint-sonarts/lib/rules/argumentsOrderRule.js:51:54)
    at Visitor.visitNode (node_modules/tslint-sonarts/lib/utils/visitor.js:350:22)
    at ts.forEachChild.child (node_modules/tslint-sonarts/lib/utils/visitor.js:585:45)
    at visitNode (node_modules/typescript/lib/typescript.js:16215:24)
    at Object.forEachChild (/node_modules/typescript/lib/typescript.js:16461:24)
    at Visitor.visitChildren (node_modules/tslint-sonarts/lib/utils/visitor.js:585:12)
    at Visitor.visitExpressionStatement (node_modules/tslint-sonarts/lib/utils/visitor.js:119:14)
    at Visitor.visitNode (node_modules/tslint-sonarts/lib/utils/visitor.js:407:22)
    at ts.forEachChild.child (node_modules/tslint-sonarts/lib/utils/visitor.js:585:45)
```

**Expected behavior**
not to throw an error.

**Comment by buffcode** [comment]
I can reproduce the exact same error using different code:

```ts
export interface Logger {
  debug: (...args: any[]) => void;
}

(({} as Logger).debug(command, args));
```

whereas the `args` parameter in line 4 when calling must be named exactly the same as in line 2.

This throws

```
ERROR: Rule error during analysis of : index.ts TypeError: Cannot read property 'name' of undefined
ERROR:     at Visitor.getSwappedPairArgument (.scannerwork\sonarts-bundle\node_modules\tslint-sonarts\lib\rules\argumentsOrderRule.js:68:47)
ERROR:     at Visitor.visitCallExpression (.scannerwork\sonarts-bundle\node_modules\tslint-sonarts\lib\rules\argumentsOrderRule.js:51:54)
ERROR:     at Visitor.visitNode (.scannerwork\sonarts-bundle\node_modules\tslint-sonarts\lib\utils\visitor.js:350:22)
ERROR:     at ts.forEachChild.child (.scannerwork\sonarts-bundle\node_modules\tslint-sonarts\lib\utils\visitor.js:585:45)
ERROR:     at visitNode (node_modules\typescript\lib\typescript.js:16135:24)
ERROR:     at Object.forEachChild (node_modules\typescript\lib\typescript.js:16333:24)
ERROR:     at Visitor.visitChildren (.scannerwork\sonarts-bundle\node_modules\tslint-sonarts\lib\utils\visitor.js:585:12)
ERROR:     at Visitor.visitParenthesizedExpression (.scannerwork\sonarts-bundle\node_modules\tslint-sonarts\lib\utils\visitor.js:215:14)
ERROR:     at Visitor.visitNode (.scannerwork\sonarts-bundle\node_modules\tslint-sonarts\lib\utils\visitor.js:494:22)
ERROR:     at ts.forEachChild.child (.scannerwork\sonarts-bundle\node_modules\tslint-sonarts\lib\utils\visitor.js:585:45)
```

Version info:
```
INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Windows 10 10.0 amd64
INFO: User cache: C:\Users\Laurens\.sonar\cache
INFO: SonarQube server 7.7.0
```

**Comment by mrdulin** [comment]
same issue.

**Comment by Mboulianne** [comment]
We've got the same issue

**Comment by vilchik-elena** [comment]
@Mboulianne can you reproduce with latest release? TS is now analyzed by SonarJS 6.1

If yes, please report it in https://github.com/SonarSource/SonarJS
