### ISSUE TITLE
TypeError: ts.formatDiagnostics is not a function

### ISSUE THREAD

**Issue by IGx89** [SonarSource/SonarTS#847]
Hello! Getting the following error when attempting to scan our TypeScript project on a new Linux machine. Any idea what the cause could be?

**SonarTS version:** 1.9<br>
**Node.js version:** 10.x (also tried 8.x)<br>
**TypeScript version:** 1.8.10<br>

**SonarQube version:** 7.7<br>

**Logs**
```
build	03-Apr-2019 12:11:48	INFO: Sensor SonarTS [typescript]
build	03-Apr-2019 12:11:48	INFO: Analyzing 121 typescript file(s) with the following configuration file /home/bamboo/bamboo-agent-home/xml-data/build-dir/SONAR-MYLTACCT2-JOB1/tsconfig.json
error	03-Apr-2019 12:11:49	ERROR: /home/bamboo/bamboo-agent-home/xml-data/build-dir/SONAR-MYLTACCT2-JOB1/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/lib/utils/parser.js:98
error	03-Apr-2019 12:11:49	ERROR:             throw new Error(ts.formatDiagnostics(errors, {
error	03-Apr-2019 12:11:49	ERROR:                                ^
error	03-Apr-2019 12:11:49	ERROR: 
error	03-Apr-2019 12:11:49	ERROR: TypeError: ts.formatDiagnostics is not a function
error	03-Apr-2019 12:11:49	ERROR:     at parseTsConfig (/home/bamboo/bamboo-agent-home/xml-data/build-dir/SONAR-MYLTACCT2-JOB1/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/lib/utils/parser.js:98:32)
error	03-Apr-2019 12:11:49	ERROR:     at Object.createProgram (/home/bamboo/bamboo-agent-home/xml-data/build-dir/SONAR-MYLTACCT2-JOB1/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/lib/utils/parser.js:66:32)
error	03-Apr-2019 12:11:49	ERROR:     at Object.processRequest (/home/bamboo/bamboo-agent-home/xml-data/build-dir/SONAR-MYLTACCT2-JOB1/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/processRequest.js:32:28)
error	03-Apr-2019 12:11:49	ERROR:     at Socket.process.stdin.on (/home/bamboo/bamboo-agent-home/xml-data/build-dir/SONAR-MYLTACCT2-JOB1/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/tsrunner.js:32:38)
error	03-Apr-2019 12:11:49	ERROR:     at emitNone (events.js:111:20)
error	03-Apr-2019 12:11:49	ERROR:     at Socket.emit (events.js:208:7)
error	03-Apr-2019 12:11:49	ERROR:     at endReadableNT (_stream_readable.js:1064:12)
error	03-Apr-2019 12:11:49	ERROR:     at _combinedTickCallback (internal/process/next_tick.js:139:11)
error	03-Apr-2019 12:11:49	ERROR:     at process._tickCallback (internal/process/next_tick.js:181:9)
error	03-Apr-2019 12:11:49	ERROR: External process `node --max-old-space-size=2048 /home/bamboo/bamboo-agent-home/xml-data/build-dir/SONAR-MYLTACCT2-JOB1/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/bin/tsrunner` returned an empty output. Run with -X for more information
build	03-Apr-2019 12:11:49	INFO: Sensor SonarTS [typescript] (done) | time=1287ms
```

**Comment by vilchik-elena** [comment]
You typescript version is not supported. From doc https://docs.sonarqube.org/display/PLUG/SonarTS :
> TypeScript version >=2.2

**Comment by IGx89** [comment]
Thank you! I was wondering if that might be the case. Just seemed pretty odd that the plugin's execution environment would be adjusting to match my app's. Magic I guess :p. I'll throw out there that a better error message might be nice in situations like this (and likely pretty easy to do), but in lieu of that having this stack now recorded in your issue tracker with the cause is probably almost as good.

Thanks a lot for the quick reply! Much appreciated.
